version: "3.7"

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress

  wordpress:
    image: "wordpress:${WORDPRESS_VERSION:-5.4}"
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html${WORDPRESS_SUBDIR}
    env_file:
      - ./.env

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.19
    ports:
      - "443:443"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html${WORDPRESS_SUBDIR}
    environment:
      NGINX_HOST_NAME: "${COMPOSE_PROJECT_NAME}"
      NGINX_UPLOADS: "${NGINX_UPLOADS}"
      WORDPRESS_SUBDIR: "${WORDPRESS_SUBDIR}"
    command: /bin/bash -c "envsubst '$$NGINX_HOST_NAME $$NGINX_UPLOADS $$WORDPRESS_SUBDIR' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/wordpress.conf && nginx -g 'daemon off;'"

  cli:
    image: wordpress:cli-2
    depends_on:
      - db
    user: xfs
    volumes:
      - .:/var/www/html${WORDPRESS_SUBDIR}

volumes:
  db-data:
