version: "3.7"

services:
  wordpress:
    volumes:
      - docker-sync:/var/www/html:nocopy

  cli:
    volumes:
      - docker-sync:/var/www/html:nocopy

  nginx:
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - docker-sync:/var/www/html${WORDPRESS_SUBDIR}:nocopy
    
volumes:
  docker-sync:
    external:
      name: ${COMPOSE_PROJECT_NAME}-wordpress-sync
